version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:8080"
    networks:
      - contenta
    volumes:
      - ./www:/var/www:cached
    # this ensures that nginx's upstream host "php" will always have
    # valid DNS when we're starting up
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - ./www:/var/www:cached
    env_file:
      - .env
    networks:
      - contenta
      - contenta_internal
    depends_on: [database]
  database:
    build: ./database
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - contenta_internal

volumes:
  data:

networks:
  contenta:
  contenta_internal:
